#!/usr/bin/env bash

#
#; bash getopts code snippet
#

NAME=""
TIMES=1

usage() {
    echo "Usage: $0 [ -n NAME ] [ -t TIMES ]" 1>&2 
}

exit_arg_err() {
  usage
  exit 1
}

# leading colon indicates silent error checking
# trailing colon indicates option requires argument
while getopts "hn:t:" opts; do 
    case "${opts}" in
        h)
            usage
            exit 0
            ;;
        n)
            NAME=${OPTARG}
            echo "NAME set as $NAME"
            ;;
        t)
            TIMES=${OPTARG}
            echo "TIMES set as $TIMES"
            ;;
        :) # only triggers when leading colon present in optargs string
            echo "[error] -${OPTARG} requires an argument"
            exit_arg_err
            ;;
        *)
            echo "[error] unknown"
            exit_arg_err
            ;;
    esac
done

exit 0

